services:
  frontend:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    container_name: lucidledger-client-prod
    ports:
      - "80:80"
    env_file:
      - ./client/.env
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    container_name: lucidledger-server-prod
    ports:
      - "5001:5001"
    env_file:
      - ./server/.env
    restart: unless-stopped
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:5001/api/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  app-network:
    driver: bridge
